## Services
google_analytics:
duoshuo:

## Meta
#rss: https://jysperm.me/atom.xml
favicon: /favicon.png
icon: /favicon.png
source_url:
license:
  name: 'CC BY-NC-SA 3.0'
  url: 'http://creativecommons.org/licenses/by-nc-sa/3.0/cn'

## Menus
menus:
  'Home': /
  'About': /about

right_menus:
#  'RSS': /atom.xml
  'theme(Github)':
    target: '_blank'
    href: 'hexo-theme-simpleblock'

## Banners && Widgets
#banners:
#  jade: |
#    a(href='https://github.com/jysperm/hexo-theme-simpleblock') 与精子同款的博客主题 simpleblock 现已发布！

widgets:
  - markdown: |
      crackhopper，85后工程师。
      
      domain：Math, CG, ML, CV, AI

      技术栈：
      * C/C++
      * Python
      * ES6/Typescript
      * C#
      
      专注与自己的游戏工作室，以及游戏引擎研发

  -
    tags: true

  -
    archives: true

  -
    copyright: true

## SNS (Work in progress)
sns:
  qq: '184300584'
  qun: '61137226'
  v2ex: 'jybox'
  mobile: '17091927884'
  github: 'jysperm'
  keybase: 'jysperm'
  zhihu: 'jysperm'
  google_plus: '+王子亭jysperm'
  segmentfault: 'jysperm'
  twitter: 'jysperm'
  bitcoin: '13v2BTCMZMHg5v87susgg86HFZqXERuwUd'
